[package]
name = "server"
version = "0.1.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.11.0"
serde = "1.0.219"
validator = { version = "0.20.0", features = ["derive"] }
