[package]
name = "route-macros"
version = "0.1.1"
edition = "2024"
license = "MIT"
rust-version = "1.85"
authors = ["Sunrisies <3266420686@qq.com>"]
description = "Procedural macros for auto-generating Actix-web CRUD handlers with OpenAPI docs"
repository = "https://github.com/Sunrisies/server"
keywords = ["actix-web", "crud", "openapi", "macros", "sea-orm"]
categories = ["web-programming", "development-tools"]

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
utoipa = "5.4.0"
route-macros-types = "0.1"

[lib]
proc-macro = true
