[package]
name = "route-macros"
version = "0.1.0"
edition = "2024"
license = "MIT"


[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
utoipa = "5.4.0"


[lib]
proc-macro = true
