//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::utils::fmt_beijing;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "external_links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub protocol: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    pub category: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub tags: Json,
    #[serde(serialize_with = "fmt_beijing")]
    pub created_at: DateTimeUtc,

    #[serde(serialize_with = "fmt_beijing")]
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl Entity {
    /// 检查唯一性约束
    pub async fn check_unique(
        db: &DatabaseConnection,
        name: String,
    ) -> Result<Option<Model>, DbErr> {
        Self::find().filter(Column::Name.eq(name)).one(db).await
    }
}
impl ActiveModelBehavior for ActiveModel {}
