//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::utils::fmt_beijing;
use sea_orm::{FromQueryResult, entity::prelude::*};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[schema(value_type = String, format = DateTime)]
    #[serde(serialize_with = "fmt_beijing")]
    pub created_at: DateTimeUtc,
}
impl Entity {
    /// 检查唯一性约束
    pub async fn check_unique(
        db: &DatabaseConnection,
        name: String,
    ) -> Result<Option<Model>, DbErr> {
        Self::find().filter(Column::Name.eq(name)).one(db).await
    }
}
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post_tags::Entity")]
    PostTags,
}

impl Related<super::post_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostTags.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        super::post_tags::Relation::Posts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::post_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
#[derive(Debug, FromQueryResult)]
pub struct PostWithCategory {
    pub id: i32,
    pub uuid: String,
    pub title: String,
    pub cover_image: Option<String>,
    pub published_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub view_count: i32,
    pub featured: bool,
    pub status: i16,
    pub summary: Option<String>,
    pub size: i32,
    pub category_id: Option<i32>,
    pub category_name: Option<String>,
}
